version: "3.9"

volumes:
  currency_postgres_data: {}

networks:
  currency-link:

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: currency_django_image:latest
    container_name: currency_django_container
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - postgres
    networks:
      - currency-link
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  postgres:
    image: "postgres:16.1-alpine3.19"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - currency_postgres_data:/var/lib/postgresql/data
    networks:
      - currency-link