# Generated by Django 5.0.1 on 2024-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bid", models.FloatField(blank=True, null=True)),
                ("ask", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
