# Generated by Django 5.0.1 on 2024-01-23 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrequest",
            options={"ordering": ("-created_at",)},
        ),
    ]
